### ISSUE TITLE
pip install servicex-cli installs 0.3.0 instead of 1.0.0rc3

### ISSUE THREAD

**Issue by AndrewEckart** [ssl-hep/servicex_cli#6]
Currently `pip install servicex-cli` installs version 0.3.0 of the CLI.

This is because all of the other versions contain "rc" in their version number. As a result, they are considered to be "Pre-Release", while 0.3.0 is considered a "Final Release" (see [PEP 440](https://www.python.org/dev/peps/pep-0440/#pre-releases)). You can see this on PyPI in the [release history](https://pypi.org/project/servicex-cli/#history) as well.

It seems that pip is defaulting to version 0.3.0 since it is the latest/only final release, which explains why @ivukotic has been having issues lately using the cli - he doesn't have the latest version.

**Comment by BenGalewsky** [comment]
Build a 1.0.0 cli version (should be safe as we doubt there will be changes before the 1.0 serviceX)
[https://pypi.org/project/servicex-cli/](https://pypi.org/project/servicex-cli/)
